#!/bin/bash

set -eu

export PORT_FILE='tests/port.list'
export ENV_FILE='tests/env.list'
export CAP_FILE='tests/cap.list'

function set_podman_aliases ()
{
    mkdir -p "${HOME}/.config/containers/registries.conf.d"
    cat << EOF > "${HOME}/.config/containers/registries.conf.d/bviktor.conf"
[aliases]
  "bviktor/ansible-systemd-almalinux" = "docker.io/bviktor/ansible-systemd-almalinux"
  "bviktor/ansible-systemd-archlinux" = "docker.io/bviktor/ansible-systemd-archlinux"
  "bviktor/ansible-systemd-fedora" = "docker.io/bviktor/ansible-systemd-fedora"
  "bviktor/ansible-systemd-lint" = "docker.io/bviktor/ansible-systemd-lint"
  "bviktor/ansible-systemd-ubuntu" = "docker.io/bviktor/ansible-systemd-ubuntu"
  "archlinux" = "docker.io/archlinux"
EOF
}

function find_exec ()
{
    # Linux Podman
    RET=0
    podman --version &> /dev/null && RET=1 || true

    if [ ${RET} -eq 1 ]
    then
        set_podman_aliases
        echo 'podman'
        return
    fi

    # Podman Remote w/ Podman Desktop on Windows
    RET=0
    podman-remote-static-linux_amd64 --version &> /dev/null && RET=1 || true

    if [ ${RET} -eq 1 ]
    then
        set_podman_aliases
        echo 'podman-remote-static-linux_amd64'
        return
    fi

    # Docker wherever
    RET=0
    docker --version &> /dev/null && RET=1 || true

    if [ ${RET} -eq 1 ]
    then
        echo 'docker'
    else
        echo ''
    fi
}

# if the given file doesn't have a trailing empty newline, add it
function fix_newline ()
{
    if [[ $(tail -c1 "${1}" | wc -l) -eq 0 ]]
    then
        echo '' >> "${1}"
    fi
}

function parse_ports ()
{
    port_str=""

    if [ ! -f "${1}" ]
    then
        echo "${port_str}"
        return
    fi

    fix_newline "${1}"

    while read -r line
    do
        if [ ! -z "$port_str" ]
        then
            port_str+=" "
        fi

        [[ $line = \#* ]] || [ -z "$line" ] && continue # skip comments & empty lines
        port_str+="-p ${line}"
    done < "${1}"

    echo "${port_str}"
}

function parse_caps ()
{
    cap_str=""

    if [ ! -f "${1}" ]
    then
        echo "${cap_str}"
        return
    fi

    fix_newline "${1}"

    while read -r line
    do
        if [ ! -z "$cap_str" ]
        then
            cap_str+=" "
        fi

        [[ $line = \#* ]] || [ -z "$line" ] && continue # skip comments & empty lines
        cap_str+="--cap-add=${line}"
    done < "${1}"

    echo "${cap_str}"
}

export exec=$(find_exec)

if [ -z "${exec}" ]
then
    echo -e "\e[31mError! Container executable not found. Ensure Podman (preferred) or Docker is installed and running.\e[0m"
    exit 1
fi

# TODO since WSL has cgroups v2, we need rw (and no --privileged), otherwise it fails
# https://github.com/moby/moby/issues/42040
if [ "${exec}" == 'docker' ]
then
    extra_flags='-v /sys/fs/cgroup:/sys/fs/cgroup:rw --tmpfs /tmp --tmpfs /run'
else
    extra_flags=''
fi

if [ ! -f 'tests/main.yml' ]
then
    echo -e "\e[31mError! Tests not found. Ensure you're in the right directory.\e[0m"
    exit 2
fi

arguments=()
platform="fedora:43"

while [[ $# -gt 0 ]]
do
    case "${1}" in
      --platform)
        platform="${2}"
        shift 2
        ;;
      *)
        arguments+=("${1}")
        shift 1
        ;;
    esac
done

role=$(basename ${PWD} | sed 's/ansible-galaxy-//')

echo -e "\nRunning Galaxy role tests on:\n - Role: \e[36m${role}\e[0m\n - Platform: \e[36m${platform}\e[0m\n - Executor: \e[36m${exec}\e[0m\n"

# Pull latest image
set +e

${exec} pull "docker.io/bviktor/ansible-systemd-${platform}"

if [ $? -eq 125 ]
then
    echo "Error pulling Docker image! Make sure to login to Docker Hub with '${exec} login docker.io' first."
    echo "If you have MFA enabled, generate an access token at https://hub.docker.com/settings/security and use that instead of your password."
    exit 1
fi

set -e

# Check for port file
PORTS=$(parse_ports "${PORT_FILE}")

# Check for capabilities file
CAPS=$(parse_caps "${CAP_FILE}")

# Fire up instance
CONT_ID=$(${exec} run --rm -v $(pwd):/repo ${PORTS} ${CAPS} ${extra_flags} --detach "bviktor/ansible-systemd-${platform}")

# Enable galaxy-rerun
${exec} exec "${CONT_ID}" bash -c "echo -e '#!/bin/bash\nANSIBLE_ROLES_PATH=.. ANSIBLE_FORCE_COLOR=true ansible-playbook ${arguments[*]} tests/main.yml' > /bin/galaxy-rerun && chmod +x /bin/galaxy-rerun"

# Install dependencies
${exec} exec "${CONT_ID}" bash -c "if [ -f requirements.yml ]; then ansible-galaxy role install --force -r requirements.yml -p ..; fi"

# Don't exit the container if errors occur
set +e

# Check for environment file
if [ -f "${ENV_FILE}" ]
then
    ENV_INC="--env-file ${ENV_FILE}"
else
    ENV_INC=''
fi

# Run the actual tests
${exec} exec ${ENV_INC} "${CONT_ID}" bash -c "ANSIBLE_ROLES_PATH=.. ANSIBLE_FORCE_COLOR=true ansible-playbook ${arguments[*]} tests/main.yml"

# Let us check stuff before exiting
${exec} exec -it "${CONT_ID}" bash

# Stop instance
${exec} stop "${CONT_ID}"
