#!/bin/bash

set -eu

function find_exec ()
{
    RET=0
    podman --version &> /dev/null && RET=1 || true

    if [ ${RET} -eq 1 ]
    then
        echo 'podman'
    else
        RET=0
        docker --version &> /dev/null && RET=1 || true

        if [ ${RET} -eq 1 ]
        then
            echo 'docker'
        else
            echo ''
        fi
    fi
}

export exec=$(find_exec)

if [ -z "${exec}" ]
then
    echo -e "\e[31mError! Container executable not found. Ensure Podman (preferred) or Docker is installed and running.\e[0m"
    exit 1
fi

# TODO since WSL has cgroups v2, we need rw (and no --privileged), otherwise it fails
# https://github.com/moby/moby/issues/42040
if [ "${exec}" == 'docker' ]
then
    extra_flags='-v /sys/fs/cgroup:/sys/fs/cgroup:rw --tmpfs /tmp --tmpfs /run'
else
    extra_flags=''
fi

if [ ! -f 'tests/main.yml' ]
then
    echo -e "\e[31mError! Tests not found. Ensure you're in the right directory.\e[0m"
    exit 2
fi

arguments=()
platform="fedora:37"

while [[ $# -gt 0 ]]
do
    case "${1}" in
      --platform)
        platform="${2}"
        shift 2
        ;;
      *)
        arguments+=("${1}")
        shift 1
        ;;
    esac
done

role=$(basename ${PWD} | sed 's/ansible-galaxy-//')

echo -e "\nRunning Galaxy role tests on:\n - Role: \e[36m${role}\e[0m\n - Platform: \e[36m${platform}\e[0m\n"

# Fire up instance
CONT_ID=$(${exec} run --rm -v $(pwd):/repo ${extra_flags} --detach "bviktor/ansible-systemd-${platform}")

# Install dependencies
${exec} exec "${CONT_ID}" bash -c "if [ -f requirements.yml ]; then ansible-galaxy role install --force -r requirements.yml -p ..; fi"

# Don't exit the container if errors occur
set +e

# Check for environment file
ENV_FILE='tests/env.list'

if [ -f "${ENV_FILE}" ]
then
    ENV_INC="--env-file ${ENV_FILE}"
else
    ENV_INC=''
fi

# Run the actual tests
${exec} exec ${ENV_INC} "${CONT_ID}" bash -c "ANSIBLE_ROLES_PATH=.. ANSIBLE_FORCE_COLOR=true ansible-playbook ${arguments[*]} tests/main.yml"

# Let us check stuff before exiting
${exec} exec -it "${CONT_ID}" bash

# Stop instance
${exec} stop "${CONT_ID}"
